name: dl-final-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # More compatible version
  - numpy
  - pandas
  - tqdm
  - transformers
  - datasets
  - requests
  - pyyaml
  - scipy
  - regex
  - tokenizers
  - huggingface_hub
  - aiohttp
  - filelock
  - fsspec
  - idna
  - multiprocess
  - pytz
  - safetensors
  - six
  - pip
  - pip:
      - aiohappyeyeballs
      - urllib3
